POST https://halalfoundation.onrender.com/updateAboutData
Content-Type: application/json

{
    "overview": "New Overview Content",
    "servicesTitle": "Agent",
    "servicesIcon": "web"
}

###

GET https://halalfoundation.onrender.com/fetchAboutData